version: 0.2

phases:
  install:
    commands:
      - echo Installing Docker...
      - yum update -y
      - yum install -y docker
      - service docker start
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  pre_build:
    commands:
      - echo Tagging the Docker image...
      - IMAGE_TAG=latest
      - REPOSITORY_NAME=my-react-app
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME
      - docker tag $REPOSITORY_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - "**/*"
  discard-paths: yes

cache:
  paths:
    - "/root/.npm/**/*"
